### ISSUE TITLE
コメントアウトについて

### ISSUE THREAD

**Issue by saotomemao** [Ryomacob21083/ProjExD#6]
https://github.com/Ryomacob21083/ProjExD/blob/2fe6741cfaefd0efad1bf4c4a281e55f7975b145/ex02/culc.py#L8

完成品だと思うのでプログラムのコメントアウトの行は消した方がよいのではないでしょうか

**Comment by Ryomacob21083** [comment]
ご指摘ありがとうございます。修正しました。
